### ISSUE TITLE
레포 타이틀을 더 제너럴 하게 바꾸는게 어떤가요

### ISSUE THREAD

**Issue by Untaek** [zel0rd/2019_AlgorithmStudy#12]
년도를 지칭하는 2019를 제외하고 algorithm-study.github.io 라던지

더 지속적인 느낌을 줄수 있을 것 같음

어떤지?

**Comment by devchanki** [comment]
괜찮은거 같아요 ㅎㅎ 년도를 빼는 것두....
음...매년 repository를 만드는 것도 괜찮을 것 같기도하고요....
아니면 년도를 지우고 폴더를 년도로 만드는것도 괜찮을거 같아요

**Comment by j3y3h0** [comment]
1. - [ ] SuwonUniversityAlgorithm
2. - [ ] 409LAB_AlgoStudy
3. - [ ] AlgorithmKing
4. - [ ] 1day1algorithm

**Comment by yuninje** [comment]
가장 심플하게 algorithm-study  을 추천합니다.

**Comment by zel0rd** [comment]
1. suwon universityalgorithm은 스터디가 확장될수도 있을꺼같아서 별로
2. 409도 이미 다른 친구들이 있어서 fail
3,4 괜찮

단 우리 프로젝트를 홍보하기 위한 페이지를 만들기위해 ~~~.github.io 식으로 제작해야함

**Comment by Untaek** [comment]
공부벌레 같은 느낌으로 algobug.github.io 어떻습니까 ㅋ

**Comment by Untaek** [comment]
goalgo.github.io 강추

**Comment by zel0rd** [comment]
의견수렴.

goalgo.github.io
